# Generated by Django 5.0.6 on 2026-08-28 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_name', models.SlugField(max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('meat', 'Meat'), ('seafood', 'Seafood'), ('dairy', 'Dairy'), ('grain', 'Grain'), ('legume', 'Legume'), ('spice', 'Spice'), ('condiment', 'Condiment'), ('baking', 'Baking'), ('oil', 'Oil'), ('beverage', 'Beverage'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('default_unit', models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('oz', 'ounces'), ('lb', 'pounds'), ('ml', 'millilitres'), ('l', 'litres'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('cup', 'cups'), ('fl_oz', 'fluid ounces'), ('piece', 'pieces'), ('clove', 'cloves'), ('slice', 'slices'), ('to_taste', 'to taste'), ('pinch', 'pinch')], default='piece', max_length=20)),
                ('is_staple', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['is_staple', 'category'], name='ingredients_is_stap_164186_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=160, unique=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ingredients.ingredient')),
            ],
            options={
                'verbose_name_plural': 'ingredient aliases',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='UnmatchedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_text', models.CharField(max_length=255, unique=True)),
                ('normalized', models.CharField(db_index=True, max_length=255)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('resolved_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ingredients.ingredient')),
            ],
            options={
                'ordering': ['-hit_count'],
            },
        ),
    ]
