# Generated by Django 5.0.6 on 2026-08-28 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientlog',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pantry_items', to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='raw_input',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
