# Generated by Django 5.0.6 on 2026-08-28 21:44

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('pantry', '0003_backfill_ingredients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pantryitem',
            options={'ordering': ['raw_input']},
        ),
        migrations.AlterUniqueTogether(
            name='pantryitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ingredientlog',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('oz', 'ounces'), ('lb', 'pounds'), ('ml', 'millilitres'), ('l', 'litres'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('cup', 'cups'), ('fl_oz', 'fluid ounces'), ('piece', 'pieces'), ('clove', 'cloves'), ('slice', 'slices'), ('to_taste', 'to taste'), ('pinch', 'pinch')], default='piece', max_length=20),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='raw_input',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('oz', 'ounces'), ('lb', 'pounds'), ('ml', 'millilitres'), ('l', 'litres'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('cup', 'cups'), ('fl_oz', 'fluid ounces'), ('piece', 'pieces'), ('clove', 'cloves'), ('slice', 'slices'), ('to_taste', 'to taste'), ('pinch', 'pinch')], default='piece', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ingredientlog',
            index=models.Index(fields=['user', '-created_at'], name='pantry_ingr_user_id_5cf0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='pantryitem',
            index=models.Index(fields=['user', 'ingredient'], name='pantry_pant_user_id_cbdf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='pantryitem',
            index=models.Index(fields=['user', 'expiry_date'], name='pantry_pant_user_id_5e7fbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='pantryitem',
            constraint=models.UniqueConstraint(fields=('user', 'ingredient'), name='uniq_user_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='pantryitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='pantry_quantity_non_negative'),
        ),
        migrations.RemoveField(
            model_name='pantryitem',
            name='ingredient_name',
        ),
    ]
