# Generated by Django 5.0.6 on 2026-09-01 03:22

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('minutes', models.PositiveIntegerField(db_index=True, null=True)),
                ('n_steps', models.PositiveSmallIntegerField(default=0)),
                ('steps', models.JSONField(default=list)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('calories', models.FloatField(null=True)),
                ('nutrition', models.JSONField(default=list, help_text='[calories, total_fat_pdv, sugar_pdv, sodium_pdv, protein_pdv, saturated_fat_pdv, carbs_pdv]')),
                ('submitted', models.DateField(null=True)),
                ('n_ingredients', models.PositiveSmallIntegerField(default=0)),
                ('n_required', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('n_unresolved', models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='recipe_tags_gin'), models.Index(fields=['n_unresolved', 'n_required'], name='recipes_rec_n_unres_07cd36_idx'), models.Index(fields=['minutes', 'n_required'], name='recipes_rec_minutes_3acccb_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=500)),
                ('is_staple', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='ingredients.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['recipe_id', 'position'],
                'indexes': [models.Index(fields=['ingredient', 'recipe'], name='recipes_rec_ingredi_bc6c07_idx'), models.Index(fields=['recipe', 'is_staple'], name='recipes_rec_recipe__e6beaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recipes_sav_user_id_845bd9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='uniq_user_saved_recipe'),
        ),
    ]
